"""migrations

Revision ID: f9882140c666
Revises: 
Create Date: 2021-12-20 21:39:08.828524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9882140c666'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructor',
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('instructor_name', sa.String(length=100), nullable=True),
    sa.Column('instructor_email', sa.String(length=100), nullable=True),
    sa.Column('instructor_adi', sa.String(length=100), nullable=True),
    sa.Column('instructor_paymentscheme', sa.String(length=100), nullable=True),
    sa.Column('instructor_password', sa.String(length=100), nullable=True),
    sa.Column('instructor_profilepic', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('instructor_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instructor')
    # ### end Alembic commands ###
